#A simple transliteration from DMG p.126

%random_dragon = (
	16 => ["White",
			["wyrmling","very young","young","juvenile","juvenile",
			 "young adult","young adult","adult","adult","mature adult",
			 "mature adult","old","old","old","very old",
			 "very old","ancient","wyrm","great wyrm","great wyrm"]],
	32 => ["Black",
			["wyrmling","wyrmling","very young","young","juvenile",
			 "juvenile","young adult","young adult","adult","adult",
			 "mature adult","mature adult","mature adult","old","old",
			 "very old","very old","ancient","wyrm","great wyrm"]],
	48 => ["Green",
			["wyrmling","wyrmling","very young","young","young",
			 "juvenile","juvenile","young adult","young adult","young adult",
			 "adult","adult","mature adult","mature adult","mature adult",
			 "old","old","very old","ancient","ancient"]],
	64 => ["Blue",
			["wyrmling","wyrmling","very young","young","young",
			 "juvenile","juvenile","young adult","young adult","young adult",
			 "adult","adult","adult","mature adult","mature adult",
			 "old","old","very old","ancient","ancient"]],
	80 => ["Red",
			["wyrmling","wyrmling","wyrmling","very young","young",
			 "young","juvenile","juvenile","juvenile","young adult",
			 "young adult","young adult","adult","adult","mature adult",
			 "mature adult","mature adult","old","old","very old"]],
	84 => ["Brass",
			["wyrmling","wyrmling","very young","young","young",
			 "juvenile","juvenile","young adult","young adult","adult",
			 "adult","mature adult","mature adult","mature adult","old",
			 "old","very old","very old","ancient","wyrm"]],
	88 => ["Copper",
			["wyrmling","wyrmling","very young","very young","young",
			 "young","juvenile","juvenile","young adult","young adult",
			 "adult","adult","adult","mature adult","mature adult",
			 "old","old","old","very old","ancient"]],
	91 => ["Bronze",
			["wyrmling","wyrmling","very young","very young","young",
			 "young","juvenile","juvenile","young adult","young adult",
			 "young adult","adult","adult","adult","mature adult",
			 "mature adult","old","old","very old","ancient"]],
	96 => ["Silver",
			["wyrmling","wyrmling","wyrmling","very young","young",
			 "young","juvenile","juvenile","juvenile","young adult",
			 "young adult","young adult","adult","adult","mature adult",
			 "mature adult","mature adult","old","old","very old"]],
	100 => ["Gold",
			["wyrmling","wyrmling","wyrmling","wyrmling","very young",
			 "very young","young","young","juvenile","juvenile",
			 "young adult","young adult","young adult","adult","adult",
			 "mature adult","mature adult","mature adult","old","old"]]
);

1;