from core_variables import *


class Periodic:
    check = {2: "Continue straight, check again in 60ft",
             5: "door",
             10: "Side passage, check again in 30ft",
             13: "Passage turns, check again in 30ft",
             16: "chamber",
             17: "stairs",
             18: "dead_end",
             19: "trap, check again in 30ft",
             20: "wandering_monster, check again for what's behind"}
    door = {6: "left", 12: "right", 20: "ahead"}
    beyond_door = {4: ["parallel passage", "10x10 room"],
                   8: "passage straight ahead",
                   9: "passage 45 degrees ahead",
                   10: "passage 45 degrees behind",
                   18: "room",
                   20: "chamber"}
    passage = {2: "left 90 degrees",
               4: "right 90 degrees",
               5: "left 45 degrees ahead",
               6: "right 45 degrees ahead",
               7: "left 45 degrees behind",
               8: "right 45 degrees behind",
               9: "left curve 45 degrees ahead",
               10: "right curve 45 degrees ahead",
               13: "passage 'T'",
               15: "passage 'Y'",
               20: "four-way intersection"}
    passage_width = {12: "10'",
                     16: "20'",
                     17: "30'",
                     18: "5'",
                     20: "SPECIAL"}
    special_passage = {4: "40', columns down center",
                       7: "40', double row of columns",
                       10: "50', double row of columns",
                       12: "50', columns 10' right and left support 10' wide upper galleries 20' above",
                       15: "10' stream",
                       17: "20' river",
                       18: "40' river",
                       19: "60' river",
                       20: "20' chasm"}
    passage_turns = {8: "left 90 degrees",
                     9: "left 45 degrees ahead",
                     10: "left 45 degress behind",
                     18: "right 90 degrees",
                     19: "right 45 degrees ahead",
                     20: "right 45 degress behind"}
    room_size = {2: "square 10x10",
                 4: "square 20x20",
                 6: "square 30x30",
                 8: "square 40x40",
                 10: "rectangle 10x20",
                 13: "rectangle 20x30",
                 15: "rectangle 20x40",
                 17: "rectangle 30x40",
                 20: "UNUSUAL"}
    chamber_size = {4: "square 20x20",
                    6: "square 30x30",
                    8: "square 40x40",
                    13: "rectangle 20x30",
                    15: "rectangle 30x50",
                    17: "rectangle 40x60",
                    20: "UNUSUAL"}
    unusual_shape = {5: "circular",
                     8: "triangular",
                     11: "trapezoidal",
                     13: "random polygon",
                     15: "oval",
                     17: "hexagonal",
                     19: "octagonal",
                     20: "cave"}
    circular_shape_has = {5: "pool", 7: "well", 10: "shaft", 20: "normal"}
    unusual_size_sqft = {3: 500,
                         6: 900,
                         8: 1300,
                         10: 2000,
                         12: 2700,
                         14: 3400,
                         20: "reroll_and_add"}
    room_stairs = {5: "down 1",
                   6: "down 2",
                   7: "down 3",
                   8: "up 1",
                   9: "up dead end, 1in6 a chute down 2",
                   10: "down dead end, 1 in 6 a chute down 1",
                   11: "chimney up 1",
                   12: "chimney up 2",
                   13: "chimney down 2",
                   16: "trapdoor down 1",
                   17: "trapdoor down 2",
                   20: "up 1, room, down 2, chamber"}
    trick_and_trap = {5: "secret door",
                      7: "pit 10' Reflex DC ? to fall in",
                      8: "pit 10' with spikes Reflex DC ? to fall in",
                      9: "20x20 elevator room, descend 1 level, reset not in this room",
                      10: "20x20 elevator room, descend 2 levels, reset not in this room",
                      11: "20x20 elevator room, descend d4+1 levels, reset not in this room",
                      12: "wall slides to block entrance hallway",
                      13: "flaming oil randomly on one PC, Reflex DC ? to save for half",
                      14: "pit 10' Reflex DC ? to fall in, walls move to crush in 2d6 rounds",
                      15: "arrow trap, d3 arrows",
                      16: "spear trap, d3 spears",
                      17: "gas, detected and covers next 60'",
                      18: "stone falls from ceiling, blocks passage, 2d10 dmg, Reflex DC ?",
                      19: "illusionary wall concealing pit/chute/chamber",
                      20: "chute down 1"}
    pit_chute_chamber = {6: "pit 10' with spikes Reflex DC ? to fall in",
                         10: "chute down 1",
                         20: "chamber with monster"}
    gas_trap = {7: "obscure vision, no other effect",
                9: "blind for d6 turns",
                12: "fear, Will DC ? or as spell",
                13: "sleep, Fort DC ? or as spell",
                18: "strength, Will DC ? or as spell",
                19: "disease, Fort DC ?",
                20: "poison, Fort DC ?"}
    cave_and_cavern = {5: "cave 40x60",
                       7: "cave 50x75",
                       9: "double cave, 20x30 and 60x60",
                       11: "double cave, 35x50 and 80x90, check for pool",
                       14: "cave 95x125, check for pool",
                       16: "cave 120x150",
                       18: "cave 150x200, check for pool",
                       20: "cavern 250-300x350-400, check for lake"}
    pool = {8: "no pool",
            10: "pool no monster",
            12: "pool and monster",
            18: "pool, monster and treasure",
            20: "magic pool"}
    magic_pool = {8: "raises one precious metal one type up (e.g. silver to gold)",
                  15: "d3 points added to one character stat",
                  17: "grant 1 wish for one alignment type",
                  20: "TELEPORT"}
    magic_teleport = {7: "back to surface",
                      12: "elsewhere on this level",
                      16: "one level down",
                      20: "to wilderness 100 miles away"}
